variables:
  IMAGE_NAME: sysnet2024/pnc_topup
  CONTAINER_NAME: pnc_topup
  ROOT_FOLDER_NAME: pnc
  PORT: 4014

stages:
  # - test
  - build
  - deploy

# run_tests:
#   stage: test
#   image: node:lts-slim
#   before_script:
#     - npm install
#   script:
#     - npm run test

build_image:
  stage: build
  image: docker:24.0.7
  services:
    - docker:24.0.7-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "$REGISTRY_PASSWORD" | docker login -u $REGISTRY_USER --password-stdin
    - echo "Logged in to Docker successfully"
  script:
    - docker build -t $IMAGE_NAME .
    - echo "Build image successfully"
    - docker push $IMAGE_NAME
    - echo "Pushed image successfully"

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY -T $HOST "
      echo "$REGISTRY_PASSWORD" | docker login -u $REGISTRY_USER --password-stdin &&
      docker stop '$CONTAINER_NAME' || true &&
      docker rm '$CONTAINER_NAME' || true &&
      docker images | grep '$IMAGE_NAME' | awk '{print $3}' | xargs docker rmi -f || true &&
      docker pull $IMAGE_NAME &&
      docker run -d -p $PORT:$PORT --name $CONTAINER_NAME --mount type=bind,source=/data/logs,target=/var/www/$ROOT_FOLDER_NAME/logs --mount type=bind,source=/data/uploads,target=/var/www/$ROOT_FOLDER_NAME/public/images $IMAGE_NAME"
